import type { Metadata } from "next";
import { Inter, Poppins } from "next/font/google";
import "@/assets/styles/main.css";
import NavBar from "@/components/nav/navbar";
import Footer from "@/components/footer/footer";
import MainHeaderBackground from "@/components/mainHeader/mainHeaderBackground";



const inter = Inter({
  variable: "--font-inter",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

// const audiowide = Audiowide({
//   variable: "--font-audiowide",
//   weight: "400",
//   subsets: ["latin"],
// });

const poppins = Poppins({
  variable: "--font-poppins",
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Planera Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${poppins.variable} antialiased`}>
        <NavBar />
        <MainHeaderBackground />
        {children}
        <Footer />
      </body>
    </html>
  );
}
